### PR TITLE
feat(miranum-stack-showcase): add showcase

### PR DESCRIPTION
**Pull request by peterhnm**
**Description**
Add a showcase that demonstrates how to use the **Miranum**-Tools all together.

**Checklist**
* [x] Code is easy to understand
* [x] No obvious errors or bugs
* [x] CI/CD Pipelines did run successfully
* [x] Tests were implemented
* [x] Documentation was created

### CODE REVIEW

**Comment by Hafflgav** [comment]
Wow, that looks super cool! 💯 🚀 
A couple of conceptual thoughts: 
1. We should port the readme's to our documentation. (happy to take care of this) 
2. Since it is a showcase in our Consulting Repository I would also point out an "easy" way to start the platform in less time than described in the eight steps. Ideally I imagine something like a stack folder containing a docker compose and build file which pulls / builds and provisions all necessary services to jump right into the Miranum-Stack. In such a scenario everything would be containerised. 

I am curious to hear your opinion on this thought!

**Comment by peterhnm** [comment]
Thank you!

1. I can do that. The place for this would be under `miranum.io > Guides > Showcases`, right?
2. Yes, you're right, I hadn't thought of that.

**Comment by Hafflgav** [comment]
> 1. I can do that. The place for this would be under `miranum.io > Guides > Showcases`, right?

Yes! That's correct! 👍

**Comment by Hafflgav** [comment]
Hey @peterhnm, can you check if starting the docker-compose after having build the project works for you now? 
It does the trick for me! 🤩

**Review by Hafflgav — APPROVED** [review]
Looks good to me and works on my machine! 🚀 
Thanks for pulling this together @peterhnm! 

Feel free to merge it once you can reproduce it on your end. 👍

**Pull request merged**
